### ISSUE TITLE
NFT/Image Tracking Support

### ISSUE THREAD

**Issue by egemenertugrul** [yannklein/arjs-webpack-boilerplate#1]
Does this project support image tracking besides Hiro markers?

https://ar-js-org.github.io/AR.js-Docs/image-tracking/

**Comment by yannklein** [comment]
Ehm, not yet! but I'll definitely put that in place when I have a bit of time! I keep you posted.

**Comment by egemenertugrul** [comment]
I see, I'm looking forward to it!
